### ISSUE TITLE
404 error Challenge does not exist

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#100]
So in the last days i noticed the "challenge" does not exist error happens a lot !!

see my recent messages and screenshots here : 
https://github.com/online-go/gtp2ogs/issues/52

this week, i got this error 4 times, thats a lot lol (didnt screenshot them all)

below is a summary of these errors

day 1 (18 january)

![challenge does not exist loop](https://user-images.githubusercontent.com/38690718/51784970-1e8aef00-2151-11e9-818d-fe0fc9f36b70.png)
![challenge loop2](https://user-images.githubusercontent.com/38690718/51784931-c94edd80-2150-11e9-839e-51ad97a48db2.png)

for this first time the challenge looped (hundreds of errors for hours)
scrolling ogs notifications, i noticed one challenge was not deleted automatically by the bot (main time too short)

then the other times, i checked but there was no challenge to be deleted on the notifications (but still triggered the "challenge does not exist error" once)

day 2 (19 january) 

![challenge error3](https://user-images.githubusercontent.com/38690718/51784927-bb995800-2150-11e9-895c-5c0cb3c6db29.png)

day 3 (yesterday) : 

![challenge error](https://user-images.githubusercontent.com/38690718/51784925-ade3d280-2150-11e9-86cc-38242623cf14.png)

day 4 (27 january) 

![challenge error4](https://user-images.githubusercontent.com/38690718/51800031-d4297100-2229-11e9-8784-d9c0c2aa084e.png)

@roy7 @tokumotoK @Dorus @windo @lemonsqueeze 

any idea why and how to fix ?

this can be very confusing for new gtp2ogs users

**Comment by TokumotoK** [comment]
As I stated in #52 
 the content in the problematic notification includes 'read' flag of '0', 'read_timestamp' of '0', so the server thinks the notification is never read when it is pushed to the browser, at least in the looping kind of the problem.

Ever since Sept. 2017 when I posted #52 , I've been getting the non-looping "Challenge does not exist" that results in freezing of gtp2ogs about once or twice a month on the average (running 3 bots almost continuously), and wondering why it does not happen or bother other gtp2ogs users.  It's been a while (months to may be a year) since I got the looping kind last time.

As anoek could not figure out, this may be a tough bug to tackle.

**Comment by wonderingabout** [comment]
every error should be fixed :)

maybe they just forgot about it, or you really were the only one who noticed it, but if thats the case we are 2 now :)

**Comment by roy7** [comment]
As far as I know, I've never seen the endless loop and never had this crash my bots. It's just one of those things I ignore. If it bothers use enough I guess we could suppress it from showing in the error log.

**Comment by wonderingabout** [comment]
the loop happened only once

as for the other messages, they happen quite often lol

once every 2-3 days for some reason

i would like to improve the log behaviour if possible

especially because this can confuse new users making them think they setup gtp2ogs.js bad or something

**Comment by windo** [comment]
I have seen something similar to this at some point on my bots too.

+1 on improving logging of decisions gtp2ogs takes with games. I think we can afford to log a few more messages for each game,

**Comment by wonderingabout** [comment]
so me, + @windo , +@tokumotoK

we are 3 persons already lol @roy7 , so it probably happened to other people too

i think it's worth trying to troobleshoot it and fix it (and maybe improve it at the same time)

**Comment by wonderingabout** [comment]
got the "challenge does not exist" error today again

![challenge error4](https://user-images.githubusercontent.com/38690718/51800022-b1975800-2229-11e9-9aa9-71b1f38eb891.png)

so yes it happens quite often @roy7 @windo @TokumotoK

**Comment by wonderingabout** [comment]
wow got the challenge loop error again today !!!

![challenge error5](https://user-images.githubusercontent.com/38690718/51801588-31302180-2240-11e9-86e4-23e3c2a271b7.png)

@roy7 @windo @Dorus

**Comment by roy7** [comment]
I know it's often, I seem them all the time in my own logs, I've just ignored it for a couple years since I don't know what causes it or how to fix it and unlike TokumotoK my bots keep working.

**Comment by wonderingabout** [comment]
no, didnt break the bot, but it could loop forever (stops only when i manually reject the game on the website)

**Comment by Dorus** [comment]
I had this too today, did some minor debugging and it seems the notification is triggered again and again. However, canceling it resulted in a 404. I didn't check network traffic, but this is an indication the error in on OGS and not gtp2ogs.

Clicking the challenge away on the web interface did remove it from my bot too, so somehow the web interface seems to send a difference cancel message than we do.

**Comment by wonderingabout** [comment]
similar problem here too again today @Dorus 

didnt get a loop this time, but this challenge is not rejected even after i refresh the webpage : 

![similar](https://user-images.githubusercontent.com/38690718/52336591-92f14800-2a05-11e9-940c-bb6ae720eceb.png)

but i noticed since i upgraded to @windo 's modules, i didnt get anymore the 404 challenge error so far, maybe its a matter of time

but here it doesnt loop
did you fix something on this issue @windo ?

![similar2](https://user-images.githubusercontent.com/38690718/52336637-b6b48e00-2a05-11e9-87fd-1a2d1b1d88b6.png)

**Comment by roy7** [comment]
It could be an OGS bug that would require @anoek to work his magic.

**Comment by wonderingabout** [comment]
maybe, i hope that whatever issues we encounter can be fixed if possible smoothly :+1: 

i'll afk a little from gtp2ogs github, i was amazed how people laughed at me as i was raising the point that gnugo bot was a trash, i expected everything but that

i hope that i can come again in better shape with quality and helpful participations in the future, cya :+1:

**Comment by sanderland** [comment]
This happened to me when I challenged my bot to an unranked match, then immediately to a ranked match, with --rankedonly.

```
Apr 27 18:53:58   [Game 23456128]  Move 373  Disconnecting from game.
Apr 27 19:04:22   #  Unranked games are not allowed on this bot.
Apr 27 19:04:22   #  Rejecting challenge from Ultimate AI (5k)  [19x19]  id = 23456907
Apr 27 19:30:40   #  Unranked games are not allowed on this bot.
Apr 27 19:30:40   #  Rejecting challenge from heiau (13k)  [9x9]  id = 23457494
Apr 27 19:37:27   #  Unranked games are not allowed on this bot.
Apr 27 19:37:27   #  Rejecting challenge from sanderl (6k)  [19x19]  id = 23457647
Apr 27 19:37:39   #  Accepting challenge from sanderl (6k)  [19x19]  id = 23457651
Apr 27 19:37:39   #  Accepting challenge from sanderl (6k)  [19x19]  id = 23457651
Apr 27 19:37:40   #  Error accepting challenge, declining it
Apr 27 19:37:40   #  Deleted notification  768720:e686c567-656d-4b73-94b8-09e736985096
Apr 27 19:37:40 !!!!! #  404 - {"error":"Challenge does not exist"}
Apr 27 19:37:40 !!!!! Error
    at conn_log (connection.js:667:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)

```

**Comment by roy7** [comment]
That sometimes happen. I'm not sure, but the log looks like it tried to accept it twice (I wonder if it was sent the challenge twice), and perhaps the 2nd time it tried to accept failed because the challenge was already deleted, from bring accepted already? You can see it's a very old error. From prior discussion it sounds like a server bug, not a gtp2ogs bug.

@anoek if it helps, it seems the accept was tried twice. Maybe the server sent the challenge twice, so it is the 2nd acceptance that gets the 404 result?
