### ISSUE TITLE
(bug) ERROR: ReferenceError: conn_log is not defined

### ISSUE THREAD

**Issue by wonderingabout** [online-go/gtp2ogs#161]
@roy7 @Dorus @windo 

using latest devel custom branch : https://github.com/wonderingabout/gtp2ogs/tree/roy7live-textonly-phoenixgo

so yet another bug today again, on top of #159 and #160 

this time, bot fails to play a move due to this error : 

```
Mar 03 08:12:42   #  Connecting to https://online-go.com:443
Mar 03 08:12:42   #  Connected
Mar 03 08:12:42   #  Bot is username: meta-金毛测试-20b
Mar 03 08:12:42   #  Bot is user id: 592558
Mar 03 09:16:36   #  igo5 wantedMinimum  Main Time , it is below Minimum Main Time live in byoyomi
Mar 03 09:16:36   #  Rejecting challenge from igo5 (4d)  [19x19]  id = 16825154
Mar 03 09:55:21   #  Accepting challenge from ソフィー (4d)  [19x19]  id = 16825464
Mar 03 09:55:28   [Game 16825464]            Connecting to game.
Mar 03 09:55:28   [Game 16825464]  Move 1    gamedata     W   ソフィー  [19x19]    
Mar 03 09:55:28   [Game 16825464]  Move 1    Starting new bot process [undefined]
Mar 03 09:55:28   [Game 16825464]  Move 1    State loading for new bot
Mar 03 09:55:28   [Game 16825464]  Move 1    genmove white
Mar 03 09:55:28 trace ERROR: Uncaught exception
Mar 03 09:55:28 !!!!! ERROR: ReferenceError: conn_log is not defined
    at ChildProcess.<anonymous> (/usr/lib/node_modules/gtp2ogs/bot.js:54:13)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Mar 03 09:57:28   [Game 16825464]  Move 1    gamedata     W   ソフィー  [19x19]    
Mar 03 09:57:28   [Game 16825464]  Move 1    Game over.   Result: B+Time      L
Mar 03 09:57:28   [undefined] Stopping bot
Mar 03 09:57:29   [Game 16825464]  Move 1    Disconnecting from game.
Mar 03 09:57:43   #  Accepting challenge from ソフィー (4d)  [19x19]  id = 16825482
Mar 03 09:57:49   [Game 16825482]            Connecting to game.
Mar 03 09:57:49   [Game 16825482]  Move 1    gamedata     W   ソフィー  [19x19]    
Mar 03 09:57:49   [Game 16825482]  Move 1    Starting new bot process [undefined]
Mar 03 09:57:49   [Game 16825482]  Move 1    State loading for new bot
Mar 03 09:57:49   [Game 16825482]  Move 1    genmove white
Mar 03 09:57:49 trace ERROR: Uncaught exception
Mar 03 09:57:49 !!!!! ERROR: ReferenceError: conn_log is not defined
    at ChildProcess.<anonymous> (/usr/lib/node_modules/gtp2ogs/bot.js:54:13)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
Mar 03 09:59:49   [Game 16825482]  Move 1    gamedata     W   ソフィー  [19x19]    
Mar 03 09:59:49   [Game 16825482]  Move 1    Game over.   Result: B+Time      L
Mar 03 09:59:49   [undefined] Stopping bot
Mar 03 09:59:50   [Game 16825482]  Move 1    Disconnecting from game.
```

![connlog bug](https://user-images.githubusercontent.com/38690718/53693106-b658aa00-3d9b-11e9-9431-179e55d602c7.png)

2 games today not able to be played because of that 

https://online-go.com/game/16825464
https://online-go.com/game/16825482

what is the cause of all these new bugs ?
any idea ?

**Comment by wonderingabout** [comment]
should be now fixed in https://github.com/wonderingabout/gtp2ogs/commit/dff2eb3c903226760951255f54435394c28a4ff0

now new error : 

![newerror](https://user-images.githubusercontent.com/38690718/53693300-eeadb780-3d9e-11e9-84df-57e71c42fcd8.png)

**Comment by wonderingabout** [comment]
oh nvm was using old command line ubuntu 16.04 `amd2018` instead of `amd2019`, should be fixed now
