### ISSUE TITLE
Uncaught error event

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#38]
I'm not sure where to try catching this so we can reconnect cleanly. My log file showed:

```
gtp2ogs.js:412                 [9553 8295806] 3:48:20 >>> genmove black
gtp2ogs.js:1003                [Game 8295806] 3:48:20 clock: {"game_id":8295806,"current_player":419331,"black_player_id":419331,"white_player_id":429266,"title":"Friendly Match","last_move":1491464900063,"expiration":1491472280063,"black_time":{"thinking_time":7200,"periods":3,"period_time":60},"white_time":{"thinking_time":7200,"periods":3,"period_time":60},"start_mode":true,"now":1491464900235}
events.js:163
throw er; // Unhandled 'error' event
^

Error: read ECONNRESET
at exports._errnoException (util.js:1033:11)
at Pipe.onread (net.js:584:26)
```

**Comment by roy7** [comment]
Giving this a try:

https://github.com/online-go/gtp2ogs/pull/42
