### ISSUE TITLE
crash in ignore_promise reading 'catch'

### ISSUE THREAD

**Issue by raylu** [online-go/gtp2ogs#410]
```
Aug 15 09:25:08   Game.ts:506          [bot  263:420990] Generating move for game 56220434
Aug 15 09:25:08   Game.ts:507          [game 56220434] genmove white
Aug 15 09:25:08   Game.ts:249          [game 56220434] Opponent played e7
Aug 15 09:25:08   Bot.ts:823           [bot  263:420990] Calling sendMove with e7
Aug 15 09:25:08 ! source-map-support.js:444 
Aug 15 09:25:08 ! source-map-support.js:445 /snapshot/bench/gtp2ogs/dist/webpack:/gtp2ogs/src/util.ts:110
    promise.catch((e) => {
            ^
Aug 15 09:25:08 ! source-map-support.js:448 TypeError: Cannot read properties of undefined (reading 'catch')
    at ignore_promise (/snapshot/bench/gtp2ogs/dist/webpack:/gtp2ogs/src/util.ts:110:13)
    at GobanSocket.on_move (/snapshot/bench/gtp2ogs/dist/webpack:/gtp2ogs/src/Game.ts:316:39)
    at GobanSocket.emit (/snapshot/bench/gtp2ogs/node_modules/eventemitter3/index.js:181:35)
    at WebSocket.<anonymous> (/snapshot/bench/gtp2ogs/dist/webpack:/gtp2ogs/goban/src/GobanSocket.ts:266:22)
    at callListener (/snapshot/bench/gtp2ogs/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/snapshot/bench/gtp2ogs/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:537:28)
    at Receiver.receiverOnMessage (/snapshot/bench/gtp2ogs/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:537:28)
    at Receiver.dataMessage (/snapshot/bench/gtp2ogs/node_modules/ws/lib/receiver.js:541:14)
```

https://github.com/online-go/gtp2ogs/blob/8ad30ce2620e145778bbd7bffa0cb0e58e7ab0c3/src/util.ts#L110

I'm on
```
$ ./gtp2ogs --version
8.0.0
```

**Comment by raylu** [comment]
I got another crash with an identical stacktrace. it was also about to `sendMove` when it happened:

```
Aug 24 05:26:54   Game.ts:249          [game 56467945] Opponent played g3
Aug 24 05:26:54   Bot.ts:823           [bot  929:1269467] Calling sendMove with g3
Aug 24 05:26:54 ! source-map-support.js:444 
Aug 24 05:26:54 ! source-map-support.js:445 /snapshot/bench/gtp2ogs/dist/webpack:/gtp2ogs/src/util.ts:110
    promise.catch((e) => {
            ^
```
