### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by anoek** [online-go/gtp2ogs#7]
Care of @tk44

``` 
gtp2ogs.js:402                 [Game 1104] Playing p16 { x: 14, y: 3, text: 'p16', resign: false, pass: false }
  gtp2ogs.js:148                 [6324] stderr:
88513 visits, 12320 nodes, 6986 vps
 
 
  gtp2ogs.js:402                 [Game 1104] Disconnecting
  gtp2ogs.js:835                 #  Connecting to game 1104
!!!!! gtp2ogs.js:319                 [TypeError: Cannot read property 'moves' of null]
C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\gtp2ogs.js:277
            if (this.state.phase == 'play') {
                          ^
 
TypeError: Cannot read property 'phase' of null
    at Game.check_for_move (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\gtp2ogs.js:277:27)
    at Socket.<anonymous> (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\gtp2ogs.js:324:13)
    at Socket.Emitter.emit (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\node_modules\component-emitter\index.js:131:20)
    at Socket.onevent (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\lib\socket.js:270:10)
    at Socket.onpacket (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\lib\socket.js:228:12)
    at Manager.<anonymous> (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\node_modules\component-bind\index.js:21:15)
    at Manager.Emitter.emit (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\node_modules\component-emitter\index.js:131:20)
    at Manager.ondecoded (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\lib\manager.js:332:8)
    at Decoder.<anonymous> (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\node_modules\component-bind\index.js:21:15)
    at Decoder.Emitter.emit (C:\cygwin64\usr\src\gtp2ogs-dev\gtp2ogs-devel\node_modules\socket.io-client\node_modules\socket.io-parser\node_modules\component-emitter\index.js:134:20)
```

**Comment by anoek** [comment]
Seems like this is no longer an issue?
