### ISSUE TITLE
State not available for clock event, --nopauseranked failing

### ISSUE THREAD

**Issue by roy7** [online-go/gtp2ogs#74]
Someone was trying this command out which I don't use myself, and apparently state isn't defined in the clock handling code so it was giving reference errors each time. Gamedata comes in before the clock does per the game log.
```

May 10 01:27:13   gtp2ogs.js:1821                #  Connected
May 10 01:27:13   gtp2ogs.js:1821                #  Bot is user id: 535375
May 10 01:27:13   gtp2ogs.js:1821                #  active_game: {"id":12805087,"phase":"play","name":"Friendly Match","player_to_move":535375,"width":19,"height":19,"move_number":2,"paused":0,"private":false,"black":{"username":"HonteMaster","id":535375,"rank":0,"professional":false,"accepted":false,"ratings":{"overall":{"rating":1500,"deviation":350,"volatility":0.06}}},"white":{"username":"Ootakamoku","id":922,"rank":30,"professional":false,"accepted":false,"ratings":{"overall":{"deviation":88.0104751992121,"rating":2476.030215438667,"volatility":0.059959680307885135,"games_played":42}}},"time_per_move":10}
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]            Connecting to game.
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]  Move 2    gamedata       B Ootakamoku  [19x19]    
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]  Move 2    makeMove 2 is 2 != 2 ?
May 10 01:27:13   gtp2ogs.js:352                 [24071] Starting  ./trollbot
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]  Move 2    Starting new bot process [24071]
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]  Move 2    State loading for new bot
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> boardsize 19
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> clear_board
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> komi 7.5
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> play black r17
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> play white d3
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> showboard
May 10 01:27:13   gtp2ogs.js:352                 [24071] Generating move for game 12805087
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]  Move 2    genmove b
May 10 01:27:13   gtp2ogs.js:352                 [24071] >>> genmove black
May 10 01:27:13   gtp2ogs.js:1027                [Game 12805087]  Move 2    clock: {"game_id":12805087,"current_player":535375,"black_player_id":535375,"white_player_id":922,"title":"Friendly Match","last_move":1525904825523,"expiration":1525904875523,"black_time":{"thinking_time":0,"periods":5,"period_time":10},"white_time":{"thinking_time":0,"periods":5,"period_time":10},"now":1525904833506}
May 10 01:27:13 trace gtp2ogs.js:266                 ERROR: Uncaught exception
May 10 01:27:13 !!!!! gtp2ogs.js:267                 ERROR: ReferenceError: state is not defined
    at Socket.<anonymous> (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/gtp2ogs.js:774:57)
    at Socket.Emitter.emit (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/component-emitter/index.js:133:20)
    at Socket.onevent (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/socket.io-client/lib/socket.js:275:10)
    at Socket.onpacket (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/socket.io-client/lib/socket.js:233:12)
    at Manager.<anonymous> (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/component-emitter/index.js:133:20)
    at Manager.ondecoded (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/socket.io-client/lib/manager.js:345:8)
    at Decoder.<anonymous> (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/component-bind/index.js:21:15)
    at Decoder.Emitter.emit (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/component-emitter/index.js:133:20)
    at Decoder.add (/home/ootakamoku/eclipse-workspace/AnalyzeGameViaGTP/gtp2ogs/node_modules/socket.io-parser/index.js:251:12)
```

**Comment by roy7** [comment]
Fixed here I think. https://github.com/online-go/gtp2ogs/commit/ae4c258fcd13ccd1d7618490fad5a6c68face038
